/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //DocsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  DocsSidebar: [
    {
      'Getting Started': ['getting-started/welcome-to-reviewpad', 'getting-started/first-revy-action:-pr-size-label'],
    },
    {
      'Use Cases': [ 'use-cases/ship-show-ask',   
      {
        type: 'category',
        label: 'Automated Labelling',
        link: { type: 'doc', id: 'use-cases/automated-labelling/automated-labelling'},
        items: [
          'use-cases/automated-labelling/label-based-on-file-paths',
          'use-cases/automated-labelling/label-based-on-author-groups',
          'use-cases/automated-labelling/label-potential-missing-changes',
          'use-cases/automated-labelling/label-critical-changes-with-code-pattern',
          'use-cases/automated-labelling/label-critical-changes-with-semantic-code-annotations',
          'use-cases/automated-labelling/remove-label-based-on-file-paths'
        ],
      },
      {
        type: 'category',
        label: 'Reviewer Assignment',
        link: { type: 'doc', id: 'use-cases/reviewer-assignment/reviewer-assignment'},
        items: [
          'use-cases/reviewer-assignment/assign-senior-reviewers-to-new-joiners',
          'use-cases/reviewer-assignment/assign-review-to-3-developers',
          'use-cases/reviewer-assignment/assign-review-to-a-team'
        ],
      },
      'use-cases/auto-merge',
      {
        type: 'category',
        label: 'Timestamps',
        link: { type: 'doc', id: 'use-cases/timestamps/timestamps'},
        items: [
          'use-cases/timestamps/notify-when-long-live-pull-request',
          'use-cases/timestamps/label-on-change-freeze',
        ],
      },
      'use-cases/comment-on-pull-requests',
      'use-cases/enforce-branch-conventions',
      'use-cases/enforce-conventional-commits',
      ],
    },
    {
      'Reviewpad File Specification': [
        'reviewpad-file-specification/introduction-to-reviewpad',
        'reviewpad-file-specification/reviewpad-syntax',
        'reviewpad-file-specification/reviewpad-semantics',
      {
        type: 'category',
        label: 'Aladino Specification',
        link: { type: 'doc', id: 'reviewpad-file-specification/aladino-specification/aladino-specification' },
        items: [
          'reviewpad-file-specification/aladino-specification/aladino-syntax',
          'reviewpad-file-specification/aladino-specification/aladino-semantics',
          'reviewpad-file-specification/aladino-specification/aladino-built-ins',
        ],
      },
      ],
    },
    {
      'Installation' : ['installation/install-reviewpad-github-action','installation/install-reviewpad-github-action-with-a-github-token'],
    },
    {
      'Tooling' : ['tooling/vscode-reviewpad-yaml-schema'],
    },
    {
      'Product Development' : ['product-development/security-information'],
    },
    {
      'Contact us' : [
        {
          type: 'link',
          label: 'Community Discord',
          href: 'https://reviewpad.com/discord',
        }
      ],
    },
    {
      'Company' : [
        {
          type: 'link',
          label: 'About us',
          href: 'https://reviewpad.com/about-us/',
        },
        {
          type: 'link',
          label: 'Blog',
          href: 'https://reviewpad.com/blog',
        },
        {
          type: 'link',
          label: 'Code Review Interface',
          href: 'https://reviewpad.com/interface-docs',
        },
        {
          type: 'link',
          label: 'Join Our Team',
          href: 'https://reviewpad.com/about-us#careers',
        },
        {
          type: 'link',
          label: 'Press Kit',
          href: 'https://reviewpad.com/press-kit',
        },
      ],
    },
    {
      'Legal' : [
        {
          type: 'link',
          label: 'Terms and Conditions',
          href: 'https://reviewpad.com/terms-and-conditions/',
        },
        {
          type: 'link',
          label: 'Privacy Policy',
          href: 'https://reviewpad.com/privacy-policy',
        },
        {
          type: 'link',
          label: 'Legal information',
          href: 'https://reviewpad.com/legal-information/',
        },
      ],
    }
  ],
};

module.exports = sidebars;
